### ISSUE TITLE
Can't build on OS X 10.9

### ISSUE THREAD

**Issue by oomathias** [redis/hiredis-node#53]
node v0.11.11

Log :

```
  > node-gyp rebuild

  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  LIBTOOL-STATIC Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:109:1: error: unknown type name 'clock_t'; did you mean 'node::clock_t'?
clock_t clock(void) __DARWIN_ALIAS(clock);
^
/usr/include/sys/_types/_clock_t.h:30:33: note: 'node::clock_t' declared here
typedef __darwin_clock_t        clock_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:110:19: error: unknown type name 'time_t'; did you mean 'node::time_t'?
char *ctime(const time_t *);
                  ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:111:17: error: unknown type name 'time_t'; did you mean 'node::time_t'?
double difftime(time_t, time_t);
                ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:111:25: error: unknown type name 'time_t'; did you mean 'node::time_t'?
double difftime(time_t, time_t);
                        ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:113:25: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *gmtime(const time_t *);
                        ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:114:28: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *localtime(const time_t *);
                           ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:115:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t mktime(struct tm *) __DARWIN_ALIAS(mktime);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:118:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time(time_t *);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:118:13: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time(time_t *);
            ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:126:21: error: unknown type name 'time_t'; did you mean 'node::time_t'?
char *ctime_r(const time_t *, char *);
                    ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:127:27: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *gmtime_r(const time_t * __restrict, struct tm * __restrict);
                          ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:128:30: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *localtime_r(const time_t * __restrict, struct tm * __restrict);
                             ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:131:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t posix2time(time_t);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:131:19: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t posix2time(time_t);
                  ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:136:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time2posix(time_t);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:136:19: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time2posix(time_t);
                  ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:137:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t timelocal(struct tm * const);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:178:
/usr/include/time.h:138:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t timegm(struct tm * const);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../deps/hiredis/hiredis.h:36:
In file included from /usr/include/sys/time.h:193:
/usr/include/sys/_select.h:39:18: error: unknown type name 'fd_set'; did you mean 'node::fd_set'?
int      select(int, fd_set * __restrict, fd_set * __restrict,
                     ^
/usr/include/sys/_types/_fd_def.h:48:3: note: 'node::fd_set' declared here
} fd_set;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.11.11/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:879:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.11.11/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ./node_modules/hiredis
gyp ERR! node -v v0.11.11
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! hiredis@0.1.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.1.16 install script.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.11.11/bin/node" "/usr/local/bin/npm" "install" "hiredis"
npm ERR! cwd ./
npm ERR! node -v v0.11.11
npm ERR! npm -v 1.3.25
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     ./npm-debug.log
npm ERR! not ok code 0
```
